[package]
name = "rast-bench"
version = "0.1.0"
edition = "2024"

[dependencies]
rast = { path = "../../../rast" }
glam = "0.30.8"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "rast"
harness = false
